### ISSUE TITLE
Hardware question.

### ISSUE THREAD

**Issue by mamin27** [marcusdechant/RadioProject#3]
Which hardware do you use for your code prototype?

**Comment by marcusdechant** [comment]
Hardware is the following.
Transmitting Radio:
Raspberry Pi Pico
Adafruit RFM95W LoRa Radio (Part ID: 3072) (915 MHz)
SHT-30 Temperature and Humidity Sensor (I2C)

Receiving Radio:
Raspberry Pi 4
Identical RFM95W Radio

RFM95W datasheet
https://www.hoperf.com/data/upload/portal/20190801/RFM96W-V2.0.pdf

**Comment by mamin27** [comment]
Thanks for the answer. I am working now at preparation of a board that integrates RP2040 (at Pico) with RFM96W  with power source from solar & wind and measurement of atmospheric pressure, humidity, temperature and meter of dust content in the air. All integrated together. If you want you could use my sensor lib for data collection (I ordered SHT25). [ecomet-i2c-sensors](https://pypi.org/project/ecomet-i2c-sensors/) Or we could cooperate together.
